apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-config-reloader
  namespace: nats-io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nats-config-reloader
rules:
- apiGroups:
  - nats.io
  resources:
  - natsclusters
  verbs:
  - "*"
- apiGroups:
  - ''
  resources:
  - "pods"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nats-config-reloader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nats-config-reloader
subjects:
- kind: ServiceAccount
  name: nats-config-reloader
  namespace: nats-io
